### ISSUE TITLE
Poprawki 

### ISSUE THREAD

**Issue by EbacWB** [vLesio/sql-translate#1]
Nie zamykanie po 1 tabeli
usuniecie przecinka w ostatnim wierszu tabeli 
możliwość wyboru języka polskiego xd

**Comment by vLesio** [comment]
Da się zrobić :d

**Comment by EbacWB** [comment]
Dzieki mordo :*

**Comment by vLesio** [comment]
Nie zamyka się po jednej tabeli, usuwa przecinek i zamienione na Polski bo wielu języków mi się nie chce :D
